// To seperate requests use ###
GET http://localhost:3001/api/notes/

###

GET http://localhost:3001/api/notes/3034

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "lol"
}

###

POST http://localhost:3001/api/notes

###

DELETE http://localhost:3001/api/notes/662be8144fc29eb4241b5337

###

GET http://localhost:3001