DELETE http://localhost:3001/api/persons/66299356b957046b76ac430d

###

GET  http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/662bf68bf36edcdf354f72f5

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "te",
    "number": 9122233 
}

###
DELETE http://localhost:3001/api/persons/662cd114ab0c89dc21a58c19
