POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "admin",
  "user": "admin",
  "password": "admin"
}

###

POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2YmZkMjAyMDc0ZjA1M2M2MjM3OWYzMSIsImlhdCI6MTcyMzg4NDY4Nn0.QvGRUMDWAnQfnZVYnHZRJq7rivryRMFfhNSgRTZrpg4

{
  "content": "rest client is a handy tool",
  "important": false
}