POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "admin2",
  "name": "admin",
  "password": "admin"
}

###

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "finalmetne",
  "author": "eunsdf",
  "url": "example.com",
  "likes": 10,
}
