POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "admin",
  "user": "admin",
  "password": "admin"
}

###

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "isto nao functiona",
  "author": "eu car",
  "url": "sklojfwel;fjea;f",
  "likes": 10,
}
